### ISSUE TITLE
Not working on raspberry pi 3 with Resin OS 2.0.8+rev1 (prod)

### ISSUE THREAD

**Issue by Temeteron** [craig-mulligan/resin-servo-node#2] opened 2017-08-12 12:45 UTC
This is the output from the resinos dashboard:

12.08.17 15:44:12 (+0300) Using hardware:                   PWM
12.08.17 15:44:12 (+0300) Number of channels:                 1
12.08.17 15:44:12 (+0300) PWM frequency:                 100 Hz
12.08.17 15:44:12 (+0300) PWM steps:                       1000
12.08.17 15:44:12 (+0300) Maximum period (100  %):      10000us
12.08.17 15:44:12 (+0300) Minimum period (0.100%):         10us
12.08.17 15:44:12 (+0300) pi-blaster: Page 0 not present (pfn 0xa100000000016864)

Obviously the problem is at the last line.

**Comment by craigmulligan** [comment] 2017-08-12 14:46
dupe of #1.

**Closed as completed by craigmulligan** 2017-08-12 14:46 UTC
